import Head from "next/head";
import Intro from "../components/views/intro";
import Experience from "../components/views/experience";
import Projects from "../components/views/projecs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jaime Trovoada</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-12">
        <Intro />
        <Experience />
        <Projects />
      </main>
    </>
  );
}
